apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/stu-10/nkp-track-field-demo
    newName: ghcr.io/stu-10/nkp-athletics-demo
    digest: sha256:c49cd9ec09069737f92cd91e89e36c525887e6a634e985a2b68a6e999f7766ab
