apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/stu-10/nkp-track-field-demo
    newName: ghcr.io/stu-10/nkp-athletics-demo
    digest: sha256:440b11f001a16e0af93765911189d8369e4a1232daed45e967b0dcd627520e42
