apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/stu-10/nkp-track-field-demo
    newName: ghcr.io/stu-10/nkp-athletics-demo
    digest: sha256:1d928c1a3ac2734afd664636725a2014f24065277164de72efb37e47fc036a67
